import type { Metadata } from 'next'
import { Zen_Kaku_Gothic_New } from 'next/font/google'
import './globals.css'

const ZenKakuGothicNew = Zen_Kaku_Gothic_New({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Maaaashi's Website",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={ZenKakuGothicNew.className}>{children}</body>
    </html>
  )
}
