name: Gauge E2E Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Linux Dependencies
        run: apt-get update && apt-get install -y curl unzip libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb wget
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set up Gauge
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
          export PATH=$PATH:$HOME/.gauge
          gauge install html-report
          gauge install java
          gauge install screenshot
          gauge install ts

      - name: Install Dependencies
        run: npm install

      - name: Set up Chrome
        run: |
          apt-get update && apt-get -y upgrade && apt-get -y autoremove
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt-get -y install ./google-chrome-stable_current_amd64.deb

      - name: Run Gauge Tests
        run: cd e2e/ && npm i && headless=Y gauge run specs

    - name: Deploy to Vercel
      if: success()
      uses: vercel/action@20.0.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}