name: Gauge E2E Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: sudo apt-get update && sudo apt-get install -y curl unzip libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - run: curl -SsL https://downloads.gauge.org/stable | sh -s -- --location-[custom path]
      - run: npm i && npm run build:e2e && npm run preview
      - run: cd e2e/ && npm i && HEADLESS=true CHROME_ARGS="--no-sandbox" gauge run specs
